version: '3.8'

services:
  mlops_app:
    build: .
    container_name: mlops_app_container
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
