apiVersion: v1
kind: Service
metadata:
  name: mlops-app-service
spec:
  type: NodePort
  selector:
    app: mlops-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080
